tilt_joint_motor:
  actuator_name: 'tilt_joint_actuator'
  serial_number: '602084008801'
  operation_mode: 'profile_position'
  clear_faults: true
  
  motor:
    type: 10

  sensor:
    type: 1
    incremental_encoder:
      resolution: 1024
      inverted_polarity: false

  safety:
    max_following_error: 20000
    max_acceleration: 15000
