rate: 10
controller_list:
  - name: fake_arm_controller
    type: interpolate
    joints:
      - j2s7s300_joint_1
      - j2s7s300_joint_2
      - j2s7s300_joint_3
      - j2s7s300_joint_4
      - j2s7s300_joint_5
      - j2s7s300_joint_6
      - j2s7s300_joint_7