#Command constants
int8 DISABLE = 0
int8 ENABLE = 1
int8 UPDATE = 2

#Response constants
int8 SUCCESS = 0
int8 ERROR = -1

#Eye shape constants
int8 NORMAL = 0
int8 CLOSE = 1
int8 CRY = 2
int8 SQUINT = 3
int8 WINK = 4
int8 MAD = 5
int8 SIDELEFT = 6
int8 HAPPY = 7
int8 SAD = 8
int8 SIDERIGHT = 9
int8 HEART = 10
int8 SLEEPY = 11
int8 HAPPY_WIDE = 12
int8 SLEEPY_WIDE = 13
int8 DEAD = 14

#Mouth shape constants
int8 FLAT = 0
int8 GRIN = 1
int8 GRIMACE = 2
int8 OPEN = 3
int8 LONGFACE = 4
int8 SMILE = 5
int8 FROWN = 6
int8 BIGOPEN = 7
int8 SQUIGGLE = 8
int8 WHISTLE = 9

#Full face constants
int8 HI = 0

#What to update
int8 EYES = 0
int8 MOUTH = 1
int8 BOTH = 2
int8 FULL_FACE = 3

#What to update for eyes
int8 DIRECTION = 0
int8 SHAPE = 1
#BOTH = 2, from above, updates direction and shape but not color
int8 COLOR = 3

#Eye directions
int8 CENTER = 0
int8 LEFT = 1
int8 RIGHT = 2

#goal definition
int8 command
int8 which_part
int8 which_feature
int8 face_shape
int8 eye_direction
int8 eye_shape
int8 eye_color
int8 mouth_direction
int8 mouth_shape
int8 mouth_color
---
#result definition
int8 response
