#Command constants
int8 DISABLE = 0
int8 ENABLE = 1
int8 SOLID = 2
int8 GRADIENT = 3

#Color constants
int8 RED = 0
int8 BLUE = 1
int8 GREEN = 2
int8 ORANGE = 3
int8 WHITE = 4

#Response constants
int8 SUCCESS = 0
int8 ERROR = -1

#goal definition
int8 command
int8 color
---
#result definition
int8 response
