# 2D Costmap parameters
# http://www.ros.org/wiki/costmap_2d

### Coordinate frame and tf parameters ###
robot_base_frame:           base_link
transform_tolerance:        0.5

robot_radius:               0.325

obstacles_costmap2d:
  observation_sources: front_scan
  front_scan: {
                sensor_frame:            /front_laser_link,
                topic:                   /scan_front,
                data_type:               LaserScan,
                inf_is_valid:            true,
                marking:                 true,
                clearing:                true,
                obstacle_range:          2.75,
                raytrace_range:          25.0}
  rear_scan: {
               sensor_frame: /rear_laser_link,
               topic:       /scan_rear,
               data_type:   LaserScan,
               marking:     true,
               clearing:    true,
               obstacle_range: 3.75,
               raytrace_range: 10.0

            }
sonar:
    topics: ["/sonar"]
    clear_on_max_reading: true
    no_readings_timeout: 2.0


inflation:
  inflation_radius:           0.4 #default 0.5
  cost_scaling_factor:        7.0 #default 10.0
