local_costmap:
    global_frame:               /odom
    robot_base_frame:           base_link
    update_frequency:           10.0
    publish_frequency:          10.0
    rolling_window:             true
    track_unknown_space:        false
    static_map:                 false
    resolution:                 0.025
    transform_tolerance:        0.1
    width: 7.0
    height: 7.0
    plugins:
        - {name: obstacles_costmap2d,       type: "costmap_2d::ObstacleLayer"}
        - {name: inflation,                 type: "costmap_2d::InflationLayer"}
    
